[package]
name = "snarkvm-synthesizer"
version = "0.14.2"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "Synthesizer for a decentralized virtual machine"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/snarkVM"
keywords = [
  "aleo",
  "cryptography",
  "blockchain",
  "decentralized",
  "zero-knowledge"
]
categories = [
  "compilers",
  "cryptography",
  "mathematics",
  "wasm",
  "web-programming"
]
include = [ "Cargo.toml", "src", "README.md", "LICENSE.md" ]
license = "Apache-2.0"
edition = "2021"

[features]
default = [ "process", "program", "snark" ]
aleo-cli = [ ]
async = [ "ledger-query/async", "synthesizer-process/async" ]
serial = [
  "console/serial",
  "ledger-block/serial",
  "ledger-query/serial",
  "ledger-store/serial",
  "synthesizer-process/serial",
  "synthesizer-program/serial",
  "synthesizer-snark/serial"
]
setup = [ ]
test = [ ]
timer = [ "aleo-std/timer" ]
wasm = [
  "process",
  "program",
  "snark",
  "console/wasm",
  "ledger-block/wasm",
  "ledger-query/wasm",
  "synthesizer-process/wasm",
  "synthesizer-program/wasm",
  "synthesizer-snark/wasm"
]
process = [ "synthesizer-process" ]
program = [ "synthesizer-program" ]
snark = [ "synthesizer-snark" ]

[dependencies.circuit]
package = "snarkvm-circuit"
path = "../circuit"
version = "=0.14.2"

[dependencies.console]
package = "snarkvm-console"
path = "../console"
version = "=0.14.2"

[dependencies.ledger-block]
package = "snarkvm-ledger-block"
path = "../ledger/block"
version = "=0.14.2"

[dependencies.ledger-query]
package = "snarkvm-ledger-query"
path = "../ledger/query"
version = "=0.14.2"
default-features = false
features = [ "query" ]

[dependencies.ledger-store]
package = "snarkvm-ledger-store"
path = "../ledger/store"
version = "=0.14.2"

[dependencies.synthesizer-process]
package = "snarkvm-synthesizer-process"
path = "./process"
version = "=0.14.2"
optional = true

[dependencies.synthesizer-program]
package = "snarkvm-synthesizer-program"
path = "./program"
version = "=0.14.2"
optional = true

[dependencies.synthesizer-snark]
package = "snarkvm-synthesizer-snark"
path = "./snark"
version = "=0.14.2"
optional = true

[dependencies.aleo-std]
version = "0.1.18"
default-features = false

[dependencies.indexmap]
version = "2.0"
features = [ "serde", "rayon" ]

[dependencies.parking_lot]
version = "0.12"

[dependencies.rand]
version = "0.8"

[dependencies.tracing]
version = "0.1"

[dev-dependencies.anyhow]
version = "1.0.71"

[dev-dependencies.itertools]
version = "0.11.0"

[dev-dependencies.once_cell]
version = "1.18"

[dev-dependencies.rayon]
version = "1"

[dev-dependencies.serde_json]
version = "1.0"
features = [ "preserve_order" ]

[dev-dependencies.serde_yaml]
version = "0.9"

[dev-dependencies.walkdir]
version = "2"
